name: MainWorkflow

on:
  pull_request:
    branches:
      - "main"
      - "master"
  release:
    types: [published]
  push:
    branches:
      - "main"
      - "master"

permissions:
  contents: read

jobs:
  # Build Job for CI
  ci-build:
    uses: ./.github/workflows/build.yaml
    with:
      build-mode: 'ci'
    if: github.event_name == 'pull_request'

  # Build Job for Release
  release-build:
    uses: ./.github/workflows/build.yaml
    with:
      build-mode: 'release'
      git-tag-version: ${{ github.ref_name }}
    if: github.event_name == 'release'

  # Release Job
  release:
    needs: release-build
    uses: ./.github/workflows/release.yaml
    with:
      artifact-name: ${{ needs.release-build.outputs.artifact-name }}
      git-tag-version: ${{ github.ref_name }}

  # Release Drafter Job
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      # https://github.com/release-drafter/release-drafter
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
            config-name: 'release-drafter.yaml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
