name: MainWorkflow

on:
  pull_request:
    branches:
      - "main"
      - "master"
  release:
    types: [published]

jobs:
  call-build-ci:
    uses: ./.github/workflows/build.yaml
    with:
      build-mode: 'ci'
    if: github.event_name == 'pull_request'

  call-build-release:
    uses: ./.github/workflows/build.yaml
    with:
      build-mode: 'release'
      git-tag-version: ${{ github.ref_name }}
    if: github.event_name == 'release'

  call-release:
    needs: call-build-release
    uses: ./.github/workflows/release.yaml
    with:
      artifact-name: ${{ needs.call-build-release.outputs.artifact-name }}
      git-tag-version: ${{ github.ref_name }}
