name: MainWorkflow

on:
  pull_request:
    branches:
      - "main"
      - "master"
  release:
    types: [published]

jobs:
  # Build Job for CI
  ci-build:
    uses: ./.github/workflows/build.yaml
    with:
      build-mode: 'ci'
    if: github.event_name == 'pull_request'

  # Build Job for Release
  release-build:
    uses: ./.github/workflows/build.yaml
    with:
      build-mode: 'release'
      git-tag-version: ${{ github.ref_name }}
    if: github.event_name == 'release'

  # Release Job
  release:
    needs: release-build
    uses: ./.github/workflows/release.yaml
    with:
      artifact-name: ${{ needs.release-build.outputs.artifact-name }}
      git-tag-version: ${{ github.ref_name }}
